function(teez_generate_embedded_runtime output_cpp runtime_dir)
    set(_marker "// Generated by teez_generate_embedded_runtime\n")
    set(_header "#include \"teez/worker/embedded_runtime.hpp\"\n\nnamespace teez::worker::embedded {\n\n")
    set(_body "")
    set(_footer "\n}  // namespace teez::worker::embedded\n")

    set(_files
        "teez-worker.lua|kTeezWorkerLua|teez_worker_lua"
        "expect.lua|kExpectLua|expect_lua"
    )

    foreach(entry IN LISTS _files)
        string(REPLACE "|" ";" _parts "${entry}")
        list(GET _parts 0 _filename)
        list(GET _parts 1 _symbol)
        list(GET _parts 2 _delimiter)

        set(_path "${runtime_dir}/${_filename}")
        if(NOT EXISTS "${_path}")
            message(FATAL_ERROR "runtime file not found: ${_path}")
        endif()

        file(READ "${_path}" _content)
        string(APPEND _body "const char* ${_symbol} = R\"${_delimiter}(\n${_content})${_delimiter}\";\n\n")
    endforeach()

    file(WRITE "${output_cpp}" "${_marker}${_header}${_body}${_footer}")
endfunction()
